### ISSUE TITLE
Undefined symbols in ETBezierHandle.o

### ISSUE THREAD

**Issue by huperniketes** [etoile/EtoilePaint#1]
I get the following errors in building Sketch on the Mac:

```
Undefined symbols for architecture x86_64:
  "_GET_PROPERTY", referenced from:
      -[ETBezierHandleGroup manipulatedObject] in ETBezierHandle.o
      -[ETBezierHandleGroup anchorPoint] in ETBezierHandle.o
      -[ETBezierHandleGroup setAnchorPoint:] in ETBezierHandle.o
      -[ETBezierHandleGroup position] in ETBezierHandle.o
      -[ETBezierHandleGroup setPosition:] in ETBezierHandle.o
      -[ETBezierHandleGroup contentBounds] in ETBezierHandle.o
      -[ETBezierHandleGroup setContentBounds:] in ETBezierHandle.o
      ...
  "_SET_PROPERTY", referenced from:
      -[ETBezierHandleGroup setManipulatedObject:] in ETBezierHandle.o
```

It seems the GET_PROPERTY() and SET_PROPERTY() macros are neither defined nor present in EtoilePaint.

**Comment by qmathe** [comment]
This framework is currently unmaintained. I might work on it again later, once I have finished to clean and stabilize [EtoileUI](https://github.com/etoile/EtoileUI), the UI toolkit that sits underneath.

Thanks for the report. I'll keep it open as a reminder for myself, but don't expect a fix soon.

**Comment by huperniketes** [comment]
Can you give me a clue what these macros did so I could manually define them myself? I could even submit a PR at that point in the (unlikely) event someone else were to try to build it.

**Comment by qmathe** [comment]
These macros were used to read/write properties stored in a dictionary. Now EtoileUI sits on top of [CoreObject](https://github.com/etoile/CoreObject) and uses it for persistency, so most EtoileUI and EtoilePaint classes have become subclasses of COObject.

They should be replaced by calls to -[COObject valueForVariableStorageKey:] and -[COObject setValue:forVariableStorageKey:]. This API is declared in [CoreObject/COObject.h](https://github.com/etoile/CoreObject/blob/master/Core/COObject.h).

You can check ETHandle.m in EtoileUI as an example.

**Comment by huperniketes** [comment]
That did indeed fix the problem. Thank you very much.
